apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-node
spec:
  replicas: 5
  selector:
    run: hello-node
  template:
    metadata:
      name: hello-node
      labels:
        run: hello-node
    spec:
      containers:
      - name: hello-node
        image: hello-node:v1
        ports:
        - containerPort: 8083
