apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  selector:
    run: hello-node
  ports:
  - port: 8083
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
